# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_motorinfos_aarch64.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_header_aarch64_pb2 as message__header__aarch64__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n message_motorinfos_aarch64.proto\x12\x0crbk.protocol\x1a\x1cmessage_header_aarch64.proto\"\xef\x03\n\x11Message_MotorInfo\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\x12\n\nmotor_name\x18\x02 \x01(\t\x12\x12\n\ncan_router\x18\x03 \x01(\r\x12\x0e\n\x06\x63\x61n_id\x18\x04 \x01(\r\x12\x10\n\x08position\x18\x05 \x01(\x02\x12\r\n\x05speed\x18\x06 \x01(\x02\x12\x0f\n\x07\x63urrent\x18\x07 \x01(\x02\x12\x0f\n\x07voltage\x18\x08 \x01(\x02\x12\x0c\n\x04stop\x18\t \x01(\x08\x12\x12\n\nerror_code\x18\n \x01(\r\x12\x0b\n\x03\x65rr\x18\x0b \x01(\x08\x12\x0b\n\x03\x65mc\x18\x0c \x01(\x08\x12\x13\n\x0btemperature\x18\r \x01(\x02\x12\x0f\n\x07\x65ncoder\x18\x0e \x01(\x05\x12\x37\n\x04type\x18\x0f \x01(\x0e\x32).rbk.protocol.Message_MotorInfo.MotorType\x12\x0f\n\x07passive\x18\x10 \x01(\x08\x12\r\n\x05\x63\x61lib\x18\x11 \x01(\x08\x12\x12\n\nfollow_err\x18\x12 \x01(\x08\x12\x14\n\x0craw_position\x18\x13 \x01(\x02\"L\n\tMotorType\x12\x08\n\x04WALK\x10\x00\x12\t\n\x05STEER\x10\x01\x12\x08\n\x04SPIN\x10\x02\x12\n\n\x06LINEAR\x10\x03\x12\x0c\n\x08ROTATION\x10\x04\x12\x06\n\x02\x44O\x10\x05\"I\n\x12Message_MotorInfos\x12\x33\n\nmotor_info\x18\x01 \x03(\x0b\x32\x1f.rbk.protocol.Message_MotorInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_motorinfos_aarch64_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_MOTORINFO']._serialized_start=81
  _globals['_MESSAGE_MOTORINFO']._serialized_end=576
  _globals['_MESSAGE_MOTORINFO_MOTORTYPE']._serialized_start=500
  _globals['_MESSAGE_MOTORINFO_MOTORTYPE']._serialized_end=576
  _globals['_MESSAGE_MOTORINFOS']._serialized_start=578
  _globals['_MESSAGE_MOTORINFOS']._serialized_end=651
# @@protoc_insertion_point(module_scope)
