# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_header.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_header.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_pb=_b('\n\x14message_header.proto\x12\x0crbk.protocol\"T\n\x0eMessage_Header\x12\x10\n\x08pub_nsec\x18\x01 \x01(\x04\x12\x11\n\tdata_nsec\x18\x02 \x01(\x04\x12\x0b\n\x03seq\x18\x03 \x01(\x04\x12\x10\n\x08\x66rame_id\x18\x04 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MESSAGE_HEADER = _descriptor.Descriptor(
  name='Message_Header',
  full_name='rbk.protocol.Message_Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pub_nsec', full_name='rbk.protocol.Message_Header.pub_nsec', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_nsec', full_name='rbk.protocol.Message_Header.data_nsec', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='rbk.protocol.Message_Header.seq', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='rbk.protocol.Message_Header.frame_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=122,
)

DESCRIPTOR.message_types_by_name['Message_Header'] = _MESSAGE_HEADER

Message_Header = _reflection.GeneratedProtocolMessageType('Message_Header', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE_HEADER,
  __module__ = 'message_header_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_Header)
  ))
_sym_db.RegisterMessage(Message_Header)


# @@protoc_insertion_point(module_scope)
