# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_controller_aarch64.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n message_controller_aarch64.proto\x12\x0crbk.protocol\"\x88\x02\n\x12Message_Controller\x12\x0c\n\x04temp\x18\x01 \x01(\x01\x12\x0c\n\x04humi\x18\x02 \x01(\x01\x12\x0f\n\x07voltage\x18\x03 \x01(\x01\x12\x0b\n\x03\x65mc\x18\x04 \x01(\x08\x12\r\n\x05\x62rake\x18\x05 \x01(\x08\x12\x11\n\tdriverEmc\x18\x06 \x01(\x08\x12\x14\n\x0cmanualCharge\x18\x07 \x01(\x08\x12\x12\n\nautoCharge\x18\x08 \x01(\x08\x12\x10\n\x08\x65lectric\x18\t \x01(\x08\x12\x0f\n\x07softEMC\x18\n \x01(\x08\x12\x19\n\x11isExternalControl\x18\x0b \x01(\x08\x12\x18\n\x10isIMUCalibrating\x18\x0c \x01(\x08\x12\x14\n\x0cvoltagebyAdc\x18\r \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_controller_aarch64_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_CONTROLLER']._serialized_start=51
  _globals['_MESSAGE_CONTROLLER']._serialized_end=315
# @@protoc_insertion_point(module_scope)
