# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_motorinfos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_header_pb2 as message__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_motorinfos.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_pb=_b('\n\x18message_motorinfos.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\"\xef\x03\n\x11Message_MotorInfo\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\x12\n\nmotor_name\x18\x02 \x01(\t\x12\x12\n\ncan_router\x18\x03 \x01(\r\x12\x0e\n\x06\x63\x61n_id\x18\x04 \x01(\r\x12\x10\n\x08position\x18\x05 \x01(\x02\x12\r\n\x05speed\x18\x06 \x01(\x02\x12\x0f\n\x07\x63urrent\x18\x07 \x01(\x02\x12\x0f\n\x07voltage\x18\x08 \x01(\x02\x12\x0c\n\x04stop\x18\t \x01(\x08\x12\x12\n\nerror_code\x18\n \x01(\r\x12\x0b\n\x03\x65rr\x18\x0b \x01(\x08\x12\x0b\n\x03\x65mc\x18\x0c \x01(\x08\x12\x13\n\x0btemperature\x18\r \x01(\x02\x12\x0f\n\x07\x65ncoder\x18\x0e \x01(\x05\x12\x37\n\x04type\x18\x0f \x01(\x0e\x32).rbk.protocol.Message_MotorInfo.MotorType\x12\x0f\n\x07passive\x18\x10 \x01(\x08\x12\r\n\x05\x63\x61lib\x18\x11 \x01(\x08\x12\x12\n\nfollow_err\x18\x12 \x01(\x08\x12\x14\n\x0craw_position\x18\x13 \x01(\x02\"L\n\tMotorType\x12\x08\n\x04WALK\x10\x00\x12\t\n\x05STEER\x10\x01\x12\x08\n\x04SPIN\x10\x02\x12\n\n\x06LINEAR\x10\x03\x12\x0c\n\x08ROTATION\x10\x04\x12\x06\n\x02\x44O\x10\x05\"I\n\x12Message_MotorInfos\x12\x33\n\nmotor_info\x18\x01 \x03(\x0b\x32\x1f.rbk.protocol.Message_MotorInfob\x06proto3')
  ,
  dependencies=[message__header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MESSAGE_MOTORINFO_MOTORTYPE = _descriptor.EnumDescriptor(
  name='MotorType',
  full_name='rbk.protocol.Message_MotorInfo.MotorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WALK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STEER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPIN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LINEAR', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROTATION', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DO', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=484,
  serialized_end=560,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_MOTORINFO_MOTORTYPE)


_MESSAGE_MOTORINFO = _descriptor.Descriptor(
  name='Message_MotorInfo',
  full_name='rbk.protocol.Message_MotorInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='rbk.protocol.Message_MotorInfo.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor_name', full_name='rbk.protocol.Message_MotorInfo.motor_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='can_router', full_name='rbk.protocol.Message_MotorInfo.can_router', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='can_id', full_name='rbk.protocol.Message_MotorInfo.can_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='rbk.protocol.Message_MotorInfo.position', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='rbk.protocol.Message_MotorInfo.speed', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current', full_name='rbk.protocol.Message_MotorInfo.current', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage', full_name='rbk.protocol.Message_MotorInfo.voltage', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stop', full_name='rbk.protocol.Message_MotorInfo.stop', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='rbk.protocol.Message_MotorInfo.error_code', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='err', full_name='rbk.protocol.Message_MotorInfo.err', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='emc', full_name='rbk.protocol.Message_MotorInfo.emc', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='rbk.protocol.Message_MotorInfo.temperature', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encoder', full_name='rbk.protocol.Message_MotorInfo.encoder', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='rbk.protocol.Message_MotorInfo.type', index=14,
      number=15, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='passive', full_name='rbk.protocol.Message_MotorInfo.passive', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='calib', full_name='rbk.protocol.Message_MotorInfo.calib', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='follow_err', full_name='rbk.protocol.Message_MotorInfo.follow_err', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='raw_position', full_name='rbk.protocol.Message_MotorInfo.raw_position', index=18,
      number=19, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGE_MOTORINFO_MOTORTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=560,
)


_MESSAGE_MOTORINFOS = _descriptor.Descriptor(
  name='Message_MotorInfos',
  full_name='rbk.protocol.Message_MotorInfos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motor_info', full_name='rbk.protocol.Message_MotorInfos.motor_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=562,
  serialized_end=635,
)

_MESSAGE_MOTORINFO.fields_by_name['header'].message_type = message__header__pb2._MESSAGE_HEADER
_MESSAGE_MOTORINFO.fields_by_name['type'].enum_type = _MESSAGE_MOTORINFO_MOTORTYPE
_MESSAGE_MOTORINFO_MOTORTYPE.containing_type = _MESSAGE_MOTORINFO
_MESSAGE_MOTORINFOS.fields_by_name['motor_info'].message_type = _MESSAGE_MOTORINFO
DESCRIPTOR.message_types_by_name['Message_MotorInfo'] = _MESSAGE_MOTORINFO
DESCRIPTOR.message_types_by_name['Message_MotorInfos'] = _MESSAGE_MOTORINFOS

Message_MotorInfo = _reflection.GeneratedProtocolMessageType('Message_MotorInfo', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE_MOTORINFO,
  __module__ = 'message_motorinfos_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_MotorInfo)
  ))
_sym_db.RegisterMessage(Message_MotorInfo)

Message_MotorInfos = _reflection.GeneratedProtocolMessageType('Message_MotorInfos', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE_MOTORINFOS,
  __module__ = 'message_motorinfos_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_MotorInfos)
  ))
_sym_db.RegisterMessage(Message_MotorInfos)


# @@protoc_insertion_point(module_scope)
