# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_odometer_aarch64.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_header_aarch64_pb2 as message__header__aarch64__pb2
import message_motorinfos_aarch64_pb2 as message__motorinfos__aarch64__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emessage_odometer_aarch64.proto\x12\x0crbk.protocol\x1a\x1cmessage_header_aarch64.proto\x1a message_motorinfos_aarch64.proto\"\x95\x02\n\x10Message_Odometer\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\r\n\x05\x63ycle\x18\x02 \x01(\r\x12\t\n\x01x\x18\x03 \x01(\x01\x12\t\n\x01y\x18\x04 \x01(\x01\x12\r\n\x05\x61ngle\x18\x05 \x01(\x02\x12\x0f\n\x07is_stop\x18\x06 \x01(\x08\x12\r\n\x05vel_x\x18\x07 \x01(\x02\x12\r\n\x05vel_y\x18\x08 \x01(\x02\x12\x12\n\nvel_rotate\x18\t \x01(\x02\x12\x13\n\x0b\x64\x65tect_skid\x18\n \x01(\x08\x12\x33\n\nmotor_info\x18\x0b \x03(\x0b\x32\x1f.rbk.protocol.Message_MotorInfo\x12\x12\n\nfollow_err\x18\x0c \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_odometer_aarch64_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_ODOMETER']._serialized_start=113
  _globals['_MESSAGE_ODOMETER']._serialized_end=390
# @@protoc_insertion_point(module_scope)
