# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_battery_aarch64.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dmessage_battery_aarch64.proto\x12\x0crbk.protocol\"\x86\x02\n\x0fMessage_Battery\x12\x11\n\tpercetage\x18\x01 \x01(\x01\x12\x16\n\x0e\x63harge_current\x18\x02 \x01(\x01\x12\x16\n\x0e\x63harge_voltage\x18\x03 \x01(\x01\x12\x13\n\x0bis_charging\x18\x04 \x01(\x08\x12\x13\n\x0btemperature\x18\x05 \x01(\x01\x12\r\n\x05\x63ycle\x18\x06 \x01(\x05\x12\x1a\n\x12max_charge_current\x18\x07 \x01(\x01\x12\x1a\n\x12max_charge_voltage\x18\x08 \x01(\x01\x12\r\n\x05\x65xtra\x18\t \x01(\t\x12\x1d\n\x15is_manually_connected\x18\n \x01(\x08\x12\x11\n\tuser_data\x18\x1e \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_battery_aarch64_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_BATTERY']._serialized_start=48
  _globals['_MESSAGE_BATTERY']._serialized_end=310
# @@protoc_insertion_point(module_scope)
