# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wrappers_aarch64.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16wrappers_aarch64.proto\x12\x0fgoogle.protobuf\"\x1c\n\x0b\x44oubleValue\x12\r\n\x05value\x18\x01 \x01(\x01\"\x1b\n\nFloatValue\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1b\n\nInt64Value\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1c\n\x0bUInt64Value\x12\r\n\x05value\x18\x01 \x01(\x04\"\x1b\n\nInt32Value\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1c\n\x0bUInt32Value\x12\r\n\x05value\x18\x01 \x01(\r\"\x1a\n\tBoolValue\x12\r\n\x05value\x18\x01 \x01(\x08\"\x1c\n\x0bStringValue\x12\r\n\x05value\x18\x01 \x01(\t\"\x1b\n\nBytesValue\x12\r\n\x05value\x18\x01 \x01(\x0c\x42S\n\x13\x63om.google.protobufB\rWrappersProtoP\x01\xa0\x01\x01\xf8\x01\x01\xa2\x02\x03GPB\xaa\x02\x1eGoogle.Protobuf.WellKnownTypesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wrappers_aarch64_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023com.google.protobufB\rWrappersProtoP\001\240\001\001\370\001\001\242\002\003GPB\252\002\036Google.Protobuf.WellKnownTypes'
  _globals['_DOUBLEVALUE']._serialized_start=43
  _globals['_DOUBLEVALUE']._serialized_end=71
  _globals['_FLOATVALUE']._serialized_start=73
  _globals['_FLOATVALUE']._serialized_end=100
  _globals['_INT64VALUE']._serialized_start=102
  _globals['_INT64VALUE']._serialized_end=129
  _globals['_UINT64VALUE']._serialized_start=131
  _globals['_UINT64VALUE']._serialized_end=159
  _globals['_INT32VALUE']._serialized_start=161
  _globals['_INT32VALUE']._serialized_end=188
  _globals['_UINT32VALUE']._serialized_start=190
  _globals['_UINT32VALUE']._serialized_end=218
  _globals['_BOOLVALUE']._serialized_start=220
  _globals['_BOOLVALUE']._serialized_end=246
  _globals['_STRINGVALUE']._serialized_start=248
  _globals['_STRINGVALUE']._serialized_end=276
  _globals['_BYTESVALUE']._serialized_start=278
  _globals['_BYTESVALUE']._serialized_end=305
# @@protoc_insertion_point(module_scope)
