# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CanFrame.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x43\x61nFrame.proto\"\xad\x01\n\x08\x43\x61nFrame\x12\n\n\x02ID\x18\x01 \x01(\r\x12\x10\n\x08\x45xtended\x18\x02 \x01(\x08\x12\x0e\n\x06Remote\x18\x03 \x01(\x08\x12\x0b\n\x03\x44LC\x18\x04 \x01(\r\x12\x0c\n\x04\x44\x61ta\x18\x05 \x01(\x0c\x12\x0f\n\x07\x43hannel\x18\x06 \x01(\r\x12\x11\n\tTimestamp\x18\x07 \x01(\r\x12\x11\n\tDirection\x18\x08 \x01(\x08\x12!\n\x08\x43\x61nerror\x18\t \x03(\x0b\x32\x0f.CanErrorRecord\"7\n\x0e\x43\x61nErrorRecord\x12\x11\n\tErrortype\x18\x01 \x01(\r\x12\x12\n\nErrorcount\x18\x02 \x01(\r*\x1b\n\tDIRE_ENUM\x12\x06\n\x02RX\x10\x00\x12\x06\n\x02TX\x10\x01*\x88\x01\n\nERROR_TYPE\x12\x0f\n\x0bSTUFF_ERROR\x10\x00\x12\x0e\n\nFORM_ERROR\x10\x01\x12\x19\n\x15\x41\x43KNOWLEDGEMENT_ERROR\x10\x02\x12\x17\n\x13\x42IT_RECESSIVE_ERROR\x10\x03\x12\x16\n\x12\x42IT_DOMINANT_ERROR\x10\x04\x12\r\n\tCRC_ERROR\x10\x05\x62\x06proto3')

_DIRE_ENUM = DESCRIPTOR.enum_types_by_name['DIRE_ENUM']
DIRE_ENUM = enum_type_wrapper.EnumTypeWrapper(_DIRE_ENUM)
_ERROR_TYPE = DESCRIPTOR.enum_types_by_name['ERROR_TYPE']
ERROR_TYPE = enum_type_wrapper.EnumTypeWrapper(_ERROR_TYPE)
RX = 0
TX = 1
STUFF_ERROR = 0
FORM_ERROR = 1
ACKNOWLEDGEMENT_ERROR = 2
BIT_RECESSIVE_ERROR = 3
BIT_DOMINANT_ERROR = 4
CRC_ERROR = 5


_CANFRAME = DESCRIPTOR.message_types_by_name['CanFrame']
_CANERRORRECORD = DESCRIPTOR.message_types_by_name['CanErrorRecord']
CanFrame = _reflection.GeneratedProtocolMessageType('CanFrame', (_message.Message,), {
  'DESCRIPTOR' : _CANFRAME,
  '__module__' : 'CanFrame_pb2'
  # @@protoc_insertion_point(class_scope:CanFrame)
  })
_sym_db.RegisterMessage(CanFrame)

CanErrorRecord = _reflection.GeneratedProtocolMessageType('CanErrorRecord', (_message.Message,), {
  'DESCRIPTOR' : _CANERRORRECORD,
  '__module__' : 'CanFrame_pb2'
  # @@protoc_insertion_point(class_scope:CanErrorRecord)
  })
_sym_db.RegisterMessage(CanErrorRecord)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DIRE_ENUM._serialized_start=251
  _DIRE_ENUM._serialized_end=278
  _ERROR_TYPE._serialized_start=281
  _ERROR_TYPE._serialized_end=417
  _CANFRAME._serialized_start=19
  _CANFRAME._serialized_end=192
  _CANERRORRECORD._serialized_start=194
  _CANERRORRECORD._serialized_end=249
# @@protoc_insertion_point(module_scope)
